name: Test wf
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - run: echo kekw!
      - name: Dump runner
        run: echo '${{ toJSON(runner) }}'
      - name: Dump gh
        run: echo '${{ toJSON(github) }}'
      - name: Dump env
        run: echo '${{ toJSON(env) }}'
      - name: Dump matrix
        run: echo '${{ toJSON(matrix) }}'
